import Link from "next/link";
import { Button } from "~/components/Button";

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center bg-white text-gray-800">
      {/* Hero Section */}
      <section className="w-full bg-gradient-to-r from-blue-600 to-indigo-700 py-20 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="flex flex-col items-center text-center">
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold text-white mb-6 leading-tight">
              Threads of Destiny
            </h1>
            <p className="text-xl sm:text-2xl text-blue-100 max-w-3xl mb-10">
              Embark on an epic journey where your choices weave the fabric of reality.
            </p>
            <Link href="/game">
              <Button variant="secondary" size="lg">
                Begin Your Adventure
              </Button>
            </Link>
          </div>
        </div>
      </section>
      
      {/* Features Section */}
      <section className="w-full py-20 px-4 bg-gray-50">
        <div className="container mx-auto max-w-6xl">
          <h2 className="text-3xl font-bold text-center mb-4 text-gray-800">How It Works</h2>
          <p className="text-lg text-center text-gray-600 mb-12 max-w-3xl mx-auto">
            <span className="font-medium">Threads of Destiny</span> is a unique choose-your-own-adventure game powered by cutting-edge AI, creating a truly personalized experience.
          </p>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="bg-white rounded-lg shadow-sm p-8 border border-gray-100 hover:shadow-md transition-shadow">
              <div className="text-blue-600 text-2xl font-bold mb-4">
                Dynamic Storytelling
              </div>
              <p className="text-gray-600">
                Leveraging the power of the ChatGPT API, the narrative unfolds based on your decisions. Explore infinite possibilities and storylines crafted in real-time.
              </p>
            </div>
            
            <div className="bg-white rounded-lg shadow-sm p-8 border border-gray-100 hover:shadow-md transition-shadow">
              <div className="text-blue-600 text-2xl font-bold mb-4">
                AI-Generated Visuals
              </div>
              <p className="text-gray-600">
                Immerse yourself in a world brought to life with unique images and character sprites generated by advanced AI, adapting to the twists and turns of your adventure.
              </p>
            </div>
          </div>
        </div>
      </section>
      
      {/* CTA Section */}
      <section className="w-full py-16 px-4 bg-white">
        <div className="container mx-auto max-w-6xl text-center">
          <h2 className="text-3xl font-bold mb-6 text-gray-800">Ready to Start Your Journey?</h2>
          <Link href="/game">
            <Button variant="primary" size="lg">
              Play Now
            </Button>
          </Link>
        </div>
      </section>
    </main>
  );
}
